spring:
  cloud:
    gateway:
      routes:

        # 1. USER AUTH SERVICE ROUTE (NO JWT FILTER HERE)
        - id: USER-AUTH-SERVICE
          uri: lb://USER-AUTH-SERVICE
        #  uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0     #  THIS IS THE FIX 
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: '#{@ipAddressKeyResolver}'

        # 2. CATALOG SERVICE ROUTE (JWT REQUIRED)
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
          filters:
            - name: JwtAuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: '#{@ipAddressKeyResolver}'
